// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqe7sJkmsAKX8v9bWfVPbN6xda5WkzqsY',
    appId: '1:196337848877:web:680d5f7691e4b947e7dea4',
    messagingSenderId: '196337848877',
    projectId: 'finlearnpro',
    authDomain: 'finlearnpro.firebaseapp.com',
    storageBucket: 'finlearnpro.firebasestorage.app',
    measurementId: 'G-2NBQEWQW83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7yKm6fUlY_jkkOmJudHdTtP_FbqsegU',
    appId: '1:196337848877:android:6d5fb8305f3a57bee7dea4',
    messagingSenderId: '196337848877',
    projectId: 'finlearnpro',
    storageBucket: 'finlearnpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ38EdEpdxtbEP7oTp3zzTTUtwrKzVF7w',
    appId: '1:196337848877:ios:fba02c4961a07febe7dea4',
    messagingSenderId: '196337848877',
    projectId: 'finlearnpro',
    storageBucket: 'finlearnpro.firebasestorage.app',
    iosBundleId: 'com.example.finnn',
  );
}
